### ISSUE TITLE
Example setup missing a comma

### ISSUE THREAD

**Issue by TC72** [nvim-telescope/telescope-hop.nvim#3]
The example set-up is missing a comma at the end of the `keys` which causes an error.

```
    hop = {
      -- keys define your hop keys in order; defaults to roughly lower- and uppercased home row
      -- shown keys here are only subset of defaults!
      keys = { "a", "s", "d", "f", "g", "h", "j", "k", "l", ";"} -- ... and more

  -- Highlight groups to link to signs and lines; the below configuration refers to demo
      -- sign_hl typically only defines foreground to possibly be combined with line_hl
      sign_hl = { "WarningMsg", "Title" },
```

**Comment by fdschmidt93** [comment]
Thanks, I'll fix the docs. The idea though here is **not** to copy the example keys but only show a subset of what the default keys are :laughing: I've realized at some points people might just blankly copy this, I'll try to make it more clear.

**Comment by fdschmidt93** [comment]
Does https://github.com/nvim-telescope/telescope-hop.nvim/commit/337a1e9f08f972ebf7a7d26251577812ebaadc78 suitably fix the issue for you?

**Comment by TC72** [comment]
Yes, I blankly copied it just to get it up and running quickly. 🤣 
And yes, that change fixes it.
